import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

/**
 * Edge function: generate-image
 *
 * Generates an image using Google Imagen 3 via Gemini API
 * and uploads it to Supabase Storage.
 *
 * Request body: {
 *   prompt: string,
 *   aspectRatio?: "1:1" | "16:9" | "9:16" | "4:3" | "3:4",
 * }
 */
serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { prompt, aspectRatio = "16:9" } = await req.json();

    if (!prompt) {
      return new Response(
        JSON.stringify({ error: "prompt is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const apiKey = Deno.env.get("GOOGLE_AI_API_KEY");
    if (!apiKey) {
      return new Response(
        JSON.stringify({ error: "GOOGLE_AI_API_KEY not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    // Generate image with Imagen 3 via Gemini API
    const genRes = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-002:predict?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          instances: [
            {
              prompt: `Professional presentation graphic: ${prompt}. Clean, modern, high quality, suitable for a business presentation slide.`,
            },
          ],
          parameters: {
            sampleCount: 1,
            aspectRatio,
          },
        }),
      },
    );

    if (!genRes.ok) {
      // Fallback: try Gemini 2.0 Flash with image generation
      const geminiRes = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${apiKey}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  {
                    text: `Generate an image: Professional presentation graphic about "${prompt}". Clean, modern, high quality, suitable for a business presentation slide.`,
                  },
                ],
              },
            ],
            generationConfig: {
              responseModalities: ["IMAGE", "TEXT"],
              responseMimeType: "image/png",
            },
          }),
        },
      );

      if (!geminiRes.ok) {
        const error = await geminiRes.text();
        throw new Error(`Google AI error: ${error}`);
      }

      const geminiData = await geminiRes.json();
      const imagePart = geminiData.candidates?.[0]?.content?.parts?.find(
        (p: any) => p.inlineData?.mimeType?.startsWith("image/"),
      );

      if (!imagePart?.inlineData?.data) {
        throw new Error("No image generated by Gemini");
      }

      // Upload base64 image to Supabase
      const imageBytes = Uint8Array.from(
        atob(imagePart.inlineData.data),
        (c) => c.charCodeAt(0),
      );

      const url = await uploadToStorage(imageBytes, "image/png");
      return new Response(
        JSON.stringify({ url }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    // Imagen 3 success path
    const data = await genRes.json();
    const imageBase64 = data.predictions?.[0]?.bytesBase64Encoded;

    if (!imageBase64) {
      throw new Error("No image in Imagen response");
    }

    const imageBytes = Uint8Array.from(atob(imageBase64), (c) => c.charCodeAt(0));
    const url = await uploadToStorage(imageBytes, "image/png");

    return new Response(
      JSON.stringify({ url }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (error) {
    console.error("Error:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});

async function uploadToStorage(
  imageBytes: Uint8Array,
  contentType: string,
): Promise<string> {
  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const supabase = createClient(supabaseUrl, supabaseKey);

  const fileName = `ai-generated/${crypto.randomUUID()}.png`;
  const { error } = await supabase.storage
    .from("presentation-assets")
    .upload(fileName, imageBytes, {
      contentType,
      cacheControl: "3600",
    });

  if (error) {
    throw new Error(`Upload error: ${error.message}`);
  }

  const { data } = supabase.storage
    .from("presentation-assets")
    .getPublicUrl(fileName);

  return data.publicUrl;
}
